### ISSUE TITLE
embeddings を訳すか

### ISSUE THREAD

**Issue by 102yuta** [259ayano/openai-cookbook-ja#6]
`embeddings`  と  `埋め込み` どちらが分かり易いだろうか

**Comment by 102yuta** [comment]
一定程度 OpenAI 特有の表現は訳さなくても（訳さない方が）分かり易いのではないか。
ドキュメントの中で統一は必要

**Comment by 102yuta** [comment]
`エンベッディング` とカタカナに訳すのはは分かり難いと思う

**Comment by 259ayano** [comment]
同じ悩みを持っていました。
どちらがいいかは迷いますが、`エンベッディング`は無しですね。

**Comment by 259ayano** [comment]
一回「埋め込み」で統一します。
